set number                  " Displaying line "
set autoindent              " Auto indent "
set smartindent             " Smart indent "
set cindent                 " C-style indent "
set tabstop=4
set shiftwidth=4
set hlsearch
set background=dark
set nocompatible
set showmatch
set title
set wmnu
set wrap
set formatoptions+=r

" Display white space "
highlight ExtraWhitespace ctermbg=red guibg=red
match ExtraWhitespace /\s\+$/

" Remove white space when the file is saved "
autocmd FileType c,cpp,java,php,javascript autocmd BufWritePre <buffer> :%s/\s\+$//e

" Display line over the 80 line
highlight OverLength ctermbg=red ctermfg=white guibg=#592929
match OverLength /\%81v.\+/

syntax on
filetype indent on

nmap <C-H> <C-W>h 
nmap <C-J> <C-W>j 
nmap <C-K> <C-W>k 
nmap <C-L> <C-W>l 
